"""
llm_config.py

Central place to configure LLM connectivity for this project:
- Backend selection (Gemini API / Vertex AI / OpenAI gateway)
- Model names
- Project / location for Vertex AI
- API keys (if you prefer to put them here instead of .env)

By default this module still respects environment variables so that you can
deploy via .env or CI secrets. For most users:

Option A (recommended):
  1) Keep your API keys and project IDs in .env
  2) Do NOT edit this file, just adjust env vars.

Option B:
  1) Edit the DEFAULT_* values below
  2) Or override via environment variables if needed.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
from typing import Literal, Optional


LLMBackend = Literal["gemini", "gemini-vertex", "openai"]


@dataclass
class LLMConfig:
    backend: LLMBackend

    # Gemini (Developer API or Vertex)
    gemini_model: str
    gemini_api_key: Optional[str]

    # Vertex AI (only used when backend == "gemini-vertex")
    gcp_project: Optional[str]
    gcp_location: str

    # OpenAI gateway (optional)
    openai_base_url: str
    openai_model: str
    openai_api_key: Optional[str]


# -------- Defaults (can be edited if you prefer code config over env) --------

DEFAULT_BACKEND: LLMBackend = "gemini"  # "gemini" | "gemini-vertex" | "openai"
DEFAULT_GEMINI_MODEL = "gemini-3.1-pro-preview"
DEFAULT_GCP_LOCATION = "global"
DEFAULT_OPENAI_BASE_URL = "https://cbsai.business.columbia.edu/api/v1"
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"


def load_llm_config() -> LLMConfig:
    """
    Load LLM configuration from environment variables, falling back to
    sensible defaults defined above. This is the single source of truth
    for llm_pipeline and any future scripts.
    """
    backend_env = os.getenv("LLM_BACKEND", DEFAULT_BACKEND).lower()
    if backend_env not in ("gemini", "gemini-vertex", "openai"):
        backend_env = DEFAULT_BACKEND
    backend: LLMBackend = backend_env  # type: ignore[assignment]

    gemini_model = os.getenv("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
    gemini_api_key = os.getenv("GEMINI_API_KEY") or None

    gcp_project = os.getenv("GOOGLE_CLOUD_PROJECT") or None
    gcp_location = os.getenv("GOOGLE_CLOUD_LOCATION", DEFAULT_GCP_LOCATION)

    openai_base_url = os.getenv("OPENAI_BASE_URL", DEFAULT_OPENAI_BASE_URL)
    openai_model = os.getenv("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)
    openai_api_key = os.getenv("OPENAI_API_KEY") or None

    return LLMConfig(
        backend=backend,
        gemini_model=gemini_model,
        gemini_api_key=gemini_api_key,
        gcp_project=gcp_project,
        gcp_location=gcp_location,
        openai_base_url=openai_base_url,
        openai_model=openai_model,
        openai_api_key=openai_api_key,
    )

